#include "GameManager.h"
#include <cstdlib>


//COSITAS HECHAS::
// 
// ------------------------------------------------------------------------------------------------------------------
// CORREGIDO EL BUG DE LAS COLISIONES, SE CAMBIO LA LOGICA PARA COLISIONAR SE UTILIZA AABB, COMO BRIAN EXPLICO
// INTEGRACION DE CLASE ABSTRACTA COLISIONABLE, DE LA CUAL HEREDAN LOS OBJETOS QUE PUEDEN COLISIONAR, 
// SE IMPLEMENTA EL METODO VIRTUAL PURO getBounds() PARA OBTENER LOS BORDES DE LOS OBJETOS Y REALIZAR LAS COLISIONES
// SE IMPLEMENTA INVENTARIO E INVENTARIO UI, SE CREAN LAS CLASES Item, Consumible, Mueble, Recurso, Equipamiento, 
// ASI COMO EL INVENTARIO Y SU INTERFAZ GRAFICA
// INTEGRACION DE LOS NUEVOS MOTORES DE OBJETOS (ItemManager y ObjectsManager) PARA CREAR Y MANEJAR LOS OBJETOS DEL JUEGO DE FORMA CENTRALIZADA
// INTEGRACION DE UN NUEVO MANAGER DE INPUT PARA CENTRALIZAR EL MANEJO DE LAS ENTRADAS DEL JUGADOR Y EVITAR DEPENDENCIAS DIRECTAS CON SFML EN OTRAS CLASES
// INTEGRACION DE UN NUEVO MANAGER DE DEBUG PARA ACTIVAR EL MODO DEBUG Y MOVER COSAS EN CALIENTE, ASI COMO MOSTRAR INFORMACIÓN DE TELEMETRÍA EN PANTALLA
// INTEGRACION DE UNA NUEVA HABILIDAD DE EJEMPLO (BolaDeFuego) PARA EL PERSONAJE, CON SU PROPIA LÓGICA DE ACTIVACIÓN, MOVIMIENTO Y COLISIONES
// INTEGRACION DE UNA NUEVA INTERFAZ DE CRÉDITOS CON SCROLL VERTICAL Y FUENTE PERSONALIZADA
// INTEGRACION DE UNA BARRA DE VIDA SOBRE LA CABEZA DE LAS ENTIDADES VIVAS (PERSONAJE, GOLEM, MASCOTA) QUE SE ACTUALIZA DINÁMICAMENTE SEGÚN SU VIDA ACTUAL
// INTEGRACION DE MEMORIA DINAMICA PARA LOS ENEMIGOS (ENEMY) PARA PODER CREAR Y DESTRUIR ENEMIGOS EN TIEMPO DE EJECUCIÓN SIN CRASHEAR EL JUEGO CON SUS IF NULLPTR
// INTEGRACION DE UN SISTEMA DE TELEMETRÍA VISUAL PARA DEBUGEAR LA IA DEL GOLEM, MOSTRANDO SU RUTA PLANIFICADA EN TIEMPO REAL Y SU RADIO DE DETECCIÓN
// INTEGRACION DE CARACTERES DE EMOJI EN LOS MENSAJES DE CONSOLA PARA HACER EL DEBUG MÁS DIVERTIDO Y VISUAL (Y PARA DEMOSTRAR QUE LA CONSOLA ESTÁ CONFIGURADA CORRECTAMENTE EN UTF-8)
//
// COSITAS PARA IMPLEMENTAR:
//
// Sistema de Guardado /serializacion para guardar el progreso del jugador (nivel, inventario, posición, etc) y cargarlo después
// Sistema de lectura de IDs especiales en el CSV para el agua (sistema de pesca) y las escaleras con efecto 2.5D (subir/bajar pisos)
// Sistema de partículas para efectos visuales (explosiones, magia, etc)
// Sistema de Pesca para el jugador
// Sistema por si el jugador muere (pantalla de muerte, reinicio de nivel, etc)
//-------------------------------------------------------------------------------------------------------------------


int main() {
	system("chcp 65001 > nul"); // Configuramos la consola para UTF-8 y ocultamos el mensaje de cambio de código (Emojis)
    GameManager game; // Instanciamos el GameManager del diagrama
    game.run();       // Ejecutamos el motor

    return 0;
}